In [1]:
# Import the dependencies.
import pandas as pd
import gmaps
import requests
# Import the API key.
from config import g_key

In [2]:
# This notebook requires that WeatherPy.ipynb is run first, to output data to the below csv file.

# Store the CSV created in WeatherPy into a dataframe.
city_data_df = pd.read_csv("weather_data/cities.csv")
city_data_df.head()

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,0,Punta Arenas,-53.1500,-70.9167,44.71,65,40,44.87,CL,2022-04-03 15:45:26
1,1,Puerto Ayora,-0.7393,-90.3518,84.16,78,89,10.60,EC,2022-04-03 15:47:01
2,2,Alindao,5.0267,21.2088,86.81,48,86,5.44,CF,2022-04-03 15:47:02
3,3,Saldanha,-33.0117,17.9442,73.45,68,0,6.69,ZA,2022-04-03 15:47:02
4,4,Albany,42.6001,-73.9662,46.17,65,100,1.01,US,2022-04-03 15:44:06

In [3]:
city_data_df.dtypes

City_ID         int64
City           object
Lat           float64
Lng           float64
Max Temp      float64
Humidity        int64
Cloudiness      int64
Wind Speed    float64
Country        object
Date           object
dtype: object

In [4]:
# Configure gmaps to use your Google API key.
gmaps.configure(api_key=g_key)

In [5]:
# Get the maximum temperature.
#max_temp = city_data_df["Max Temp"]
#temps = []
#for temp in max_temp:
#    temps.append(max(temp, 0))

In [6]:
# Heatmap of temperature
# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]

# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]

# Assign the figure variable.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)

# Assign the heatmap variable.
heat_layer = gmaps.heatmap_layer(locations,
                                 weights=[max(temp, 0) for temp in max_temp],
                                 dissipating=False,
                                 max_intensity=300,
                                 point_radius=4)

# Add the heatmap layer.
fig.add_layer(heat_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [7]:
# Heatmap of percent humidity
locations = city_data_df[["Lat", "Lng"]]
humidity = city_data_df["Humidity"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations,
                                 weights=humidity,
                                 dissipating=False,
                                 max_intensity=300,
                                 point_radius=4)

fig.add_layer(heat_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [8]:
# Heatmap of percent cloudiness
locations = city_data_df[["Lat", "Lng"]]
clouds = city_data_df["Cloudiness"]
fig = gmaps.figure(center=(30.0, 31.0),
                   zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations,
                                 weights=clouds,
                                 dissipating=False,
                                 max_intensity=300,
                                 point_radius=4)

fig.add_layer(heat_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [9]:
# Heatmap of Wind Speed
locations = city_data_df[["Lat", "Lng"]]
wind = city_data_df["Wind Speed"]
fig = gmaps.figure(center=(30.0, 31.0),
                   zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations,
                                 weights=wind,
                                 dissipating=False,
                                 max_intensity=300,
                                 point_radius=4)

fig.add_layer(heat_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [10]:
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 70
What is the maximum temperature you would like for your trip? 90

In [11]:
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)].dropna()
preferred_cities_df.head(10)

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
1,1,Puerto Ayora,-0.7393,-90.3518,84.16,78,89,10.60,EC,2022-04-03 15:47:01
2,2,Alindao,5.0267,21.2088,86.81,48,86,5.44,CF,2022-04-03 15:47:02
3,3,Saldanha,-33.0117,17.9442,73.45,68,0,6.69,ZA,2022-04-03 15:47:02
5,5,Cape Town,-33.9258,18.4232,73.11,66,40,12.66,ZA,2022-04-03 15:42:35
6,6,Chuy,-33.6971,-53.4616,72.30,66,100,11.86,UY,2022-04-03 15:47:02
9,9,Rikitea,-23.1203,-134.9692,76.10,64,44,9.04,PF,2022-04-03 15:47:03
12,12,Saint-Philippe,-21.3585,55.7679,74.79,88,100,16.13,RE,2022-04-03 15:47:04
13,13,Kapaa,22.0752,-159.3190,72.12,84,20,18.41,US,2022-04-03 15:44:54
16,16,Axim,4.8699,-2.2405,85.14,73,100,12.12,GH,2022-04-03 15:44:10
17,17,Ouro Preto Do Oeste,-10.7481,-62.2158,84.34,70,47,1.68,BR,2022-04-03 15:47:05

In [12]:
preferred_cities_df.notnull().sum()

City_ID       220
City          220
Lat           220
Lng           220
Max Temp      220
Humidity      220
Cloudiness    220
Wind Speed    220
Country       220
Date          220
dtype: int64

In [13]:
# Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City","Country","Max Temp","Lat","Lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

                   City Country  Max Temp      Lat       Lng Hotel Name
1          Puerto Ayora      EC     84.16  -0.7393  -90.3518
2               Alindao      CF     86.81   5.0267   21.2088
3              Saldanha      ZA     73.45 -33.0117   17.9442
5             Cape Town      ZA     73.11 -33.9258   18.4232
6                  Chuy      UY     72.30 -33.6971  -53.4616
9               Rikitea      PF     76.10 -23.1203 -134.9692
12       Saint-Philippe      RE     74.79 -21.3585   55.7679
13                Kapaa      US     72.12  22.0752 -159.3190
16                 Axim      GH     85.14   4.8699   -2.2405
17  Ouro Preto Do Oeste      BR     84.34 -10.7481  -62.2158

In [14]:
# Set parameters to search for a hotel
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

In [18]:
# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    # Grab the first hotel from the results and store the name.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [19]:
hotel_df

,City,Country,Max Temp,Lat,Lng,Hotel Name
1,Puerto Ayora,EC,84.16,-0.7393,-90.3518,Finch Bay Galapagos Hotel
2,Alindao,CF,86.81,5.0267,21.2088,OCHA Alindao
3,Saldanha,ZA,73.45,-33.0117,17.9442,Blue Bay Lodge
5,Cape Town,ZA,73.11,-33.9258,18.4232,"Radisson Blu Hotel Waterfront, Cape Town"
6,Chuy,UY,72.30,-33.6971,-53.4616,Nuevo Hotel Plaza
...,...,...,...,...,...,...
551,Qandala,SO,82.76,11.4720,49.8728,
553,Bacolod,PH,78.22,10.6667,122.9500,Planta Hotel & Residences
559,Saint-Joseph,RE,73.78,-21.3667,55.6167,"""Plantation Bed and Breakfast"
560,Belmonte,BR,84.07,-15.8631,-38.8828,Pousada Monte Carmelo O Pão
562,Takoradi,GH,87.37,4.8845,-1.7554,Raybow International Hotel

In [20]:
# Add a heatmap of temperature for the vacation spots.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0),
                   zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations,
                                 weights=max_temp,
                                 dissipating=False,
                                 max_intensity=300,
                                 point_radius=4)

fig.add_layer(heat_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [22]:
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

In [23]:
# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

In [24]:
# Add a heatmap of temperature for the vacation spots and a pop-up marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations,
                                 weights=max_temp,
                                 dissipating=False,
                                 max_intensity=300,
                                 point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))